name: Generate Gradient Background

on:
  push:
    branches:
      - main

jobs:
  generate-background:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install Pillow

    - name: Generate Gradient Image
      run: python generate_gradient.py

    - name: Upload Gradient Image
      uses: actions/upload-artifact@v2
      with:
        name: gradient
        path: gradient.png
